name: Publish GA-Scrap to PyPI

on:
  push:
    tags:
      - 'v*.*.*'    # v1.2.3 টাইপ ট্যাগ দিলে ট্রিগার হবে
  workflow_dispatch: #manuall

jobs:
  build:
    name: Build and Publish to PyPI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Build the package
        run: python -m build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
